name: Docker Hub Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: 11

      - name: Testing gradlew publish
        run: ./gradlew :pushAllDockerImages -Pdocker-pull-licenses -Pdocker-tag=${RELEASE}rc${RC_NUM} -Pjava11Home=${JAVA11_HOME}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: elink21
      #     password: ${{secrets.DOCKER_TOKEN}}
          
      # - name: Generate Simple Docker file
      #   run: |
      #     echo "FROM ubuntu:20.04" >> Dockerfile
      # # - name: Docker build
      # #   run: docker build . -t elink21/dockerhubtest:latest
      # # - name: Push to dockerhub
      # #   run: docker push elink21/dockerhubtest:latest
    